### ISSUE TITLE
Build plugin

### ISSUE THREAD

**Issue by jbrockopp** [go-vela/vela-terraform#1]
## Description

_What is your idea?_

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

## Definition of Done

_What is the end goal of this story?_

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

## Impacted Personas (Optional)

_Which personas will benefit from completing this story? (Users, Administrators, etc)_

**Comment by kneal** [comment]
_First push with baseline code_
https://github.com/go-vela/vela-terraform/commit/1ba0ba109c76433f7df3f9baa596340861a2024d

**Comment by kneal** [comment]
_enhancements to add plugin skeletons_
https://github.com/go-vela/vela-terraform/pull/3

**Comment by kneal** [comment]
_add the ability to execute apply command_
https://github.com/go-vela/vela-terraform/pull/4

**Comment by kneal** [comment]
Update to use the new plugin style:
https://github.com/go-vela/vela-terraform/pull/14
